# PW2
### Numpy revision and image basics with OpenCV

In [ ]:
import numpy as np

## Creating Arrays

In [ ]:
arr=np.array([0,1,2,3,4])

In [ ]:
arr

array([0, 1, 2, 3, 4])

In [ ]:
#using arange
array=np.arange(0,10)
array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#using arange
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
#zeros matrix
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#ones matrix
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Operations

In [ ]:
# a random array of 10 elements (elements between 0 and 100)
arr=np.random.randint(0,100,10)

In [ ]:
arr

array([23, 62,  4,  3, 93, 80, 81, 82, 14, 65])

In [ ]:
#another array
arr2=np.random.randint(0,100,10)

In [ ]:
arr2

array([ 6,  4, 12, 45, 62, 15, 85, 64,  0, 46])

In [ ]:
#max (the largest element within an array)
max=np.max(arr)
max

93

In [ ]:
#min (the smallest element within an array)
min=np.min(arr)
min

3

In [ ]:
#mean: average of all elements
mean=np.mean(arr)
mean

50.7

In [ ]:
#reshape (2,5)
arr.reshape(2,5)

array([[23, 62,  4,  3, 93],
       [80, 81, 82, 14, 65]])

## Indexing

In [ ]:
#create a matrix 10x10
mat = np.random.randint(0, 100, size=(10, 10))
mat

array([[84, 81, 57, 78, 79, 77,  1, 69, 13, 50],
       [87, 24, 68,  3, 28, 60, 46, 51, 73, 82],
       [63, 37, 66, 78, 18, 55, 78, 34, 15,  2],
       [26, 19,  2, 13, 29, 65, 98, 96, 73, 20],
       [56,  6, 55, 70, 60, 96, 62, 18, 17, 41],
       [ 2, 21, 34, 89, 62, 86, 53, 26, 84, 56],
       [64, 78, 94, 78, 93, 88, 45, 86, 77, 55],
       [72, 76, 98, 44, 70, 30, 55, 44,  3, 70],
       [87, 37, 61, 75, 84,  5, 95, 38, 83, 73],
       [87, 75, 90, 63, 53, 90,  5, 41, 10,  3]])

In [ ]:
row = 0
col = 1

In [ ]:
mat[row,col]

81

In [ ]:
# With Slices
mat[:,col]

array([81, 24, 37, 19,  6, 21, 78, 76, 37, 75])

In [ ]:
mat[row,:]

array([84, 81, 57, 78, 79, 77,  1, 69, 13, 50])

In [ ]:
mat[0:3,0:3]

array([[84, 81, 57],
       [87, 24, 68],
       [63, 37, 66]])